/**
 * Receipts are generated server-side at handover and stored append-only
 * (§3.12). Content is a fixed JSON shape plus its SHA-256.
 */
import type { Tx } from "@/lib/db/client";
import * as s from "@/lib/db/schema";
import { humanCode, sha256Hex } from "@/lib/crypto/random";
import { tzDay } from "@/lib/util/time";
import type { Order, PaidTotals } from "./payments";

export interface ReceiptContent {
  v: 1;
  receiptNo: string;
  orderRef: string;
  verifyRef: string;
  product: string;
  quantity: number;
  priceTzs: number;
  paidTzs: number;
  donorFundedTzs: number;
  date: string;
  note: string;
}

export async function createReceipt(tx: Tx, order: Order, productName: string, totals: PaidTotals): Promise<{ receiptNo: string }> {
  const receiptNo = `RC-${tzDay().replace(/-/g, "")}-${humanCode(5)}`;
  const content: ReceiptContent = {
    v: 1,
    receiptNo,
    orderRef: order.ref,
    verifyRef: order.verifyRef,
    product: productName,
    quantity: order.quantity,
    priceTzs: order.totalTzs,
    paidTzs: totals.confirmedTzs,
    donorFundedTzs: totals.donorTzs,
    date: tzDay(),
    note: "Generated by the system at handover. No automatic deductions, no late fees, no debt.",
  };
  await tx.insert(s.receipts).values({ orderId: order.id, receiptNo, content, contentSha256: sha256Hex(JSON.stringify(content)) });
  return { receiptNo };
}
